apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataingestionservicedb-deployment
  namespace: energyco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataingestionservicedb
  template:
    metadata:
      labels:
        app: dataingestionservicedb
    spec:
      containers:
        - name: dataingestionservicedb
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "dataingestionservicedb"
            - name: POSTGRES_USER
              value: "userauthuser"
            - name: POSTGRES_PASSWORD
              value: "userauthpassword"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
