apiVersion: v1
kind: Service
metadata:
  name: dataingestionservicedb-service
  namespace: energyco
spec:
  selector:
    app: dataingestionservicedb
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
  type: ClusterIP
