apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataingestionservice-deployment
  namespace: energyco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataingestionservice
  template:
    metadata:
      labels:
        app: dataingestionservice
    spec:
      containers:
        - name: dataingestionservice
          image: victodomvar/dataingestionservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://dataingestionservicedb-service:5433/dataingestionservicedb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "dataingestionuser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "dataingestionpassword"
