apiVersion: v1
kind: Service
metadata:
  name: dataingestionservice-service
  namespace: energyco
spec:
  selector:
    app: dataingestionservice
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081
  type: ClusterIP
